name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag git-parser-ui:$(date +%s)
      
    - name: Login in docker
      run: docker login -u=${{ secrets.DOCKER_HUB_LOGIN }} -p=${{ secrets.DOCKER_HUB_PASSWORD }}
      
    - name: Push to docker hub
      run: docker push git-parser-ui:$(date +%s)
    

